// スタイル定義
export const styles = {
  page: {
    backgroundColor: "#f7fafc",
    minHeight: "100vh",
    color: "#2d3748",
    fontFamily: "sans-serif",
  },
  nav: {
    backgroundColor: "#fff",
    position: "sticky",
    top: 0,
    zIndex: 100,
    borderBottom: "1px solid #e2e8f0",
  },
  navInner: {
    display: "flex",
    height: 60,
    padding: "0 20px",
    alignItems: "center",
  },
  sidebar: { width: 220, flexShrink: 0 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 25,
    border: "1px solid #edf2f7",
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  badge: {
    fontSize: "0.7rem",
    color: "#fff",
    padding: "2px 6px",
    borderRadius: 4,
    fontWeight: "bold",
  },
  primaryButton: {
    padding: 10,
    backgroundColor: "#1a365d",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: "bold",
  },
  secondaryButton: {
    padding: 10,
    backgroundColor: "#3182ce",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
    fontWeight: "bold",
  },
  pageBtn: {
    padding: "8px 14px",
    borderRadius: 6,
    border: "1px solid #cbd5e0",
    background: "#fff",
    color: "#2d3748",
    cursor: "pointer",
    fontWeight: "bold",
    fontSize: "0.9rem",
    transition: "all 0.2s",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 30,
    maxWidth: 800,
    width: "100%",
    maxHeight: "90vh",
    overflowY: "auto",
    position: "relative",
  },
  spinner: {
    width: 40,
    height: 40,
    border: "4px solid rgba(0,191,165,0.2)",
    borderTopColor: "#00bfa5",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    margin: "40px auto",
  },
  attachmentSection: {
    marginTop: 15,
    paddingTop: 12,
    borderTop: "1px dashed #e2e8f0",
  },
  attachmentLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: "0.85rem",
    color: "#3182ce",
    textDecoration: "none",
    marginRight: 12,
    marginBottom: 4,
    fontWeight: "500",
  },
};
